import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";

const exo = Exo({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <main className="flex h-screen bg-slate-900 items-center justify-center">
          <div className="m-auto max-w-screen-md flex-1">
            <div className="w-full rounded-3xl bg-slate-800 p-8 shadow-lg">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
